/**
 * The example skills, inlined.
 *
 * Inlined rather than fetched so the page has a real set on first paint with no request, and
 * generated from examples/ by scripts/sync-examples.mjs so the copy here cannot drift from
 * the ones the CLI is tested against.
 */
export const EXAMPLES: readonly string[] = [
  "---\nname: changelog-entry\ndescription: Write a changelog entry from a merged diff, in the voice of someone telling a user what changed for them rather than what moved in the code. Use after merging a pull request, when preparing a release, or when a changelog line reads like a commit message. Triggers on \"write the changelog\", \"changelog entry\", \"what shipped\", \"release notes\".\n---\n\n# Changelog entry\n\nA changelog is read by someone deciding whether to upgrade. It is not a commit log.\n\n## Rules\n\n1. **Lead with what the reader can now do**, or what stopped happening to them. Not the\n   file that changed.\n2. **One entry per user-visible change.** Three commits that together fix one bug are one\n   entry.\n3. **Name the surface.** \"Fixed a crash\" is unactionable; \"Fixed a crash when importing a\n   CSV with no header row\" tells a reader whether it affects them.\n4. **No entry for internal work** unless it changes behaviour, performance or an interface.\n   A refactor with identical behaviour is invisible by design.\n\n## Shape\n\n```\n### Fixed\n- Importing a CSV with no header row no longer crashes the preview.\n```\n\nGroup under Added, Changed, Fixed, Removed. Drop any group that is empty rather than\nprinting it with nothing under it.\n",
  "---\nname: flaky-test-triage\ndescription: Decide whether a failing test found a real bug, is flaky, or is asserting the wrong thing, before anyone changes the code it guards. Use when a test fails intermittently, when CI is red on a rerun that passed, or when someone proposes deleting or retrying a test. Triggers on \"flaky test\", \"test failed in CI\", \"it passes locally\", \"just rerun it\", \"quarantine the test\".\n---\n\n# Flaky test triage\n\n\"Rerun it\" is a decision to ship without knowing. Make the decision deliberately instead.\n\n## Three outcomes, and only three\n\n**Real failure.** The test is right and the code is wrong. Fix the code.\n\n**Flaky.** The test is right about intent but wrong about determinism: it depends on wall\nclock, ordering, a shared fixture, network, or a race. Fix the determinism, not the\nassertion.\n\n**Wrong assertion.** The test encodes a belief that was never true, or stopped being true\ndeliberately. Fix the test, and say which of the two it was.\n\n## How to tell them apart\n\nRun it in isolation, then in its own suite, then with the suite shuffled. A test that\npasses alone and fails in a suite is sharing state with a sibling. A test that fails in\nboth is real until proven otherwise.\n\nRun it twenty times. A failure rate near 100% is real; near 50% is a race; near 1% is\nusually a timeout that is too tight for a loaded runner.\n\n**Check whether it has ever passed for the right reason.** A test that has been green since\nit was written may have been vacuous from the start, in which case its first failure is the\nfirst time it did its job.\n\n## The rule that matters\n\n**Never quarantine a test without an owner and a date.** A quarantined test with neither is\na deleted test that still costs runtime.\n",
];
